### ISSUE TITLE
Gauges with alias get counted incorrect on jotak:mm branch when using influx

### ISSUE THREAD

**Issue by bckfnn** [vert-x3/vertx-monitoring#13]
When a Match is added that aliases a Gauge with a high cardinality tag like vertx.eventbus.handlers,address into _ the counting that is send to influx seems to go wrong.

In my program 

      https://gist.github.com/bckfnn/6f46f1a3bcc8cc3820d86a2dc36830cc

I add a few handlers:

        vertx.eventBus().localConsumer("abc", $ -> {});
        vertx.eventBus().localConsumer("abc", $ -> {});
        vertx.eventBus().localConsumer("abc", $ -> {});
        vertx.eventBus().localConsumer("def", $ -> {});
        vertx.eventBus().localConsumer("def", $ -> {});
        vertx.eventBus().localConsumer("gih", $ -> {});

and the data to influx is correct:

vertx_eventbus_handlers,address=abc,metric_type=gauge value=3 1518300608048
vertx_eventbus_handlers,address=gih,metric_type=gauge value=1 1518300608049
vertx_eventbus_handlers,address=def,metric_type=gauge value=2 1518300608049

but when an alias is added:

        metricsOpts.addLabelMatch(new Match()
                .setDomain(MetricsCategory.EVENT_BUS)
                .setLabel("address")
                .setType(MatchType.REGEX)
                .setValue(".*")
                .setAlias("_"));

only one of the Meters (the first?) is send to influx:

vertx_eventbus_handlers,address=_,metric_type=gauge value=3 1518300784628

I believe the count should have been 6.

**Comment by jotak** [comment]
I'll look into this today, thanks for reporting

**Comment by jotak** [comment]
This should be fixed

**Comment by bckfnn** [comment]
Yes, it is look very good. Thank you for the prompt fix.
